<a href="https://colab.research.google.com/github/hyoshincopy/dacon/blob/master/%EB%8D%B0%EC%9D%B4%EC%BD%98%EC%8B%AC%EB%A6%AC%EC%84%B1%ED%96%A5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
import lightgbm as lgbm
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
#경로 설정을 꼭 신경써주세요!!
train=pd.read_csv('./train.csv', index_col=0) #인덱스 col=0도 check!
test=pd.read_csv('./test_x.csv', index_col=0)
submission=pd.read_csv('./sample_submission.csv', index_col=0)

In [ ]:
train

       QaA   QaE  QbA   QbE  QcA  ...  wr_09  wr_10  wr_11  wr_12  wr_13
index                             ...
0      3.0   363  4.0  1370  5.0  ...      0      1      0      1      1
1      5.0   647  5.0  1313  3.0  ...      0      1      0      1      1
2      4.0  1623  1.0  1480  1.0  ...      1      1      0      1      1
3      3.0   504  3.0  2311  4.0  ...      0      1      0      1      1
4      1.0   927  1.0   707  5.0  ...      0      1      1      1      1
...    ...   ...  ...   ...  ...  ...    ...    ...    ...    ...    ...
45527  2.0  1050  5.0   619  4.0  ...      1      1      0      1      1
45528  2.0   581  3.0  1353  4.0  ...      1      1      0      1      1
45529  4.0   593  1.0   857  1.0  ...      0      1      0      1      1
45530  1.0   747  3.0  1331  4.0  ...      1      1      0      1      1
45531  3.0   496  5.0  1827  5.0  ...      0      1      0      1      1

[45532 rows x 77 columns]

In [ ]:
train_x = train.drop('voted', axis = 1)
train_y = train['voted']

In [ ]:
gender = {'Male': 1,'Female': 2} 
religion ={'Agnostic':1, 'Atheist':2, 'Buddhist':3, 'Christian_Catholic':4, 'Christian_Mormon':5, 'Christian_Protestant':6, 'Christian_Other':7, 'Hindu':8, 'Jewish':9, 'Muslim':10, 'Sikh':11, 'Other':12}
race={'Asian':1, 'Arab':2, 'Black':3, 'Indigenous Australian':4, 'Native American':5, 'White':6, 'Other':7}

In [ ]:
age_group = {'10s': 1,'20s': 2,'30s':3,'40s':4,'50s':5,'60s':6,'+70s':7}

In [ ]:
train_x.gender = [gender[item] for item in train_x.gender] 
train_x.religion = [religion[item] for item in train_x.religion] 
train_x.race = [race[item] for item in train_x.race]

In [ ]:
train_x.age_group = [age_group[item] for item in train_x.age_group]

In [ ]:
test.gender = [gender[item] for item in test.gender] 
test.religion = [religion[item] for item in test.religion] 
test.race = [race[item] for item in test.race] 
test.age_group = [age_group[item] for item in test.age_group]

In [ ]:
train_x

       QaA   QaE  QbA   QbE  QcA  ...  wr_09  wr_10  wr_11  wr_12  wr_13
index                             ...
0      3.0   363  4.0  1370  5.0  ...      0      1      0      1      1
1      5.0   647  5.0  1313  3.0  ...      0      1      0      1      1
2      4.0  1623  1.0  1480  1.0  ...      1      1      0      1      1
3      3.0   504  3.0  2311  4.0  ...      0      1      0      1      1
4      1.0   927  1.0   707  5.0  ...      0      1      1      1      1
...    ...   ...  ...   ...  ...  ...    ...    ...    ...    ...    ...
45527  2.0  1050  5.0   619  4.0  ...      1      1      0      1      1
45528  2.0   581  3.0  1353  4.0  ...      1      1      0      1      1
45529  4.0   593  1.0   857  1.0  ...      0      1      0      1      1
45530  1.0   747  3.0  1331  4.0  ...      1      1      0      1      1
45531  3.0   496  5.0  1827  5.0  ...      0      1      0      1      1

[45532 rows x 76 columns]

In [ ]:
model = lgbm.LGBMClassifier(n_estimators=500)
model.fit(train_x, train_y)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=500, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [ ]:
pred_y = model.predict(test)

In [ ]:
pred_y

array([2, 2, 1, ..., 1, 1, 2])

In [ ]:
submission['voted']=pred_y

In [ ]:
submission

       voted
index
0          2
1          2
2          1
3          1
4          2
...      ...
11378      1
11379      2
11380      1
11381      1
11382      2

[11383 rows x 1 columns]

In [ ]:
submission.to_csv('./sample_submission.csv')

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

forest_model=RandomForestRegressor(random_state=1)
forest_model.fit(train_x, train_y)
# melb_preds = forest_model.predict(val_X)
# print(mean_absolute_error(val_y, melb_preds))

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=1, verbose=0, warm_start=False)

In [ ]:
pred_y=forest_model.predict(test)

In [ ]:
submission['voted']=pred_y

In [ ]:
submission

       voted
index
0       1.67
1       1.75
2       1.40
3       1.23
4       1.81
...      ...
11378   1.43
11379   1.94
11380   1.17
11381   1.40
11382   1.49

[11383 rows x 1 columns]

In [ ]:
train_y

index
0        2
1        2
2        1
3        1
4        1
        ..
45527    2
45528    2
45529    1
45530    1
45531    1
Name: voted, Length: 45532, dtype: int64

In [ ]:
submission.to_csv('./sample_submission2.csv')

In [ ]:
train_x.head()

       QaA   QaE  QbA   QbE  QcA  ...  wr_09  wr_10  wr_11  wr_12  wr_13
index                             ...
0      3.0   363  4.0  1370  5.0  ...      0      1      0      1      1
1      5.0   647  5.0  1313  3.0  ...      0      1      0      1      1
2      4.0  1623  1.0  1480  1.0  ...      1      1      0      1      1
3      3.0   504  3.0  2311  4.0  ...      0      1      0      1      1
4      1.0   927  1.0   707  5.0  ...      0      1      1      1      1

[5 rows x 76 columns]

In [ ]:
cnt=0
for i in train_x:
   cnt+=1
   if cnt%2!=0 and cnt<41:
     train_x[i]=list(map(int,(train_x[i])))

In [ ]:
train_x

       QaA   QaE  QbA   QbE  QcA  ...  wr_09  wr_10  wr_11  wr_12  wr_13
index                             ...
0        3   363    4  1370    5  ...      0      1      0      1      1
1        5   647    5  1313    3  ...      0      1      0      1      1
2        4  1623    1  1480    1  ...      1      1      0      1      1
3        3   504    3  2311    4  ...      0      1      0      1      1
4        1   927    1   707    5  ...      0      1      1      1      1
...    ...   ...  ...   ...  ...  ...    ...    ...    ...    ...    ...
45527    2  1050    5   619    4  ...      1      1      0      1      1
45528    2   581    3  1353    4  ...      1      1      0      1      1
45529    4   593    1   857    1  ...      0      1      0      1      1
45530    1   747    3  1331    4  ...      1      1      0      1      1
45531    3   496    5  1827    5  ...      0      1      0      1      1

[45532 rows x 76 columns]

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import mean_absolute_error

forest_model=ExtraTreesClassifier(random_state=3)
forest_model.fit(train_x, train_y)
# melb_preds = forest_model.predict(val_X)
# print(mean_absolute_error(val_y, melb_preds))

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100,
                     n_jobs=None, oob_score=False, random_state=3, verbose=0,
                     warm_start=False)

In [ ]:
pred_y=forest_model.predict(test)
forest_model.

In [ ]:
submission['voted']=pred_y

In [ ]:
submission

       voted
index
0          2
1          2
2          1
3          1
4          2
...      ...
11378      1
11379      2
11380      1
11381      1
11382      2

[11383 rows x 1 columns]

In [ ]:
submission.to_csv('./sample_submission5.csv')

In [ ]:
# a=pd.read_csv('./sample_submission4.csv')
# b=pd.read_csv('./sample_submission5.csv')

In [ ]:
# cnt=0
# for i in range(len(a['voted'])):
#   if a['voted'][i]!=b['voted'][i]:
#     cnt+=1

# cnt

NameError: ignored